Homepage updates
arachne-threat-intel/thread pull request #29
Opened 2022-03-15 01:21 UTC by jecarr

2022-03-19 21:49 UTC, KadeMorton requested changes

2022-03-19 21:49 UTC, KadeMorton commented on threadcomponents/service/rest_svc.py
> +        criteria['title'] = [criteria.get('title', '')]
Do checks if title or url are missing

2022-03-21 01:33 UTC, jecarr commented on threadcomponents/service/rest_svc.py
> +        criteria['title'] = [criteria.get('title', '')]
Resolved in a4ece16

2022-03-22 07:30 UTC, KadeMorton approved these changes

2022-03-22 07:30 UTC, KadeMorton commented
Discussed and merged

2022-03-22 07:30 UTC, merged