Recognise and display indicators of compromise
arachne-threat-intel/thread pull request #46
Opened 2023-02-27 03:41 UTC by msariego-endgame

2023-02-27 16:48 UTC, jecarr commented
*Excuse my base-branch tampering - I noted some commits were from the previous PR but I think that's because I did a rebase rather than a merge (so the changes are coming up again)

2023-03-03 13:34 UTC, jecarr requested changes
Really liking the style of this, just a front-end tweak to do.

I did add two commits - pdf column widths and permission checks. The latter is a chunkier commit so feel free to contest how I did it/improve where you feel is best.

2023-03-05 02:29 UTC, KadeMorton commented on threadcomponents/handlers/web_api.py
> +        dd['content'].append(dict(table=ioc_table))
@jecarr no that's fine.

2023-03-06 02:13 UTC, msariego-endgame commented on webapp/theme/scripts/basics.js
> +  $(iocSwitchSelector).prop("checked", sentenceIsIoc);
Oh, you're correct.
Thanks for noticing it!

2023-03-06 13:10 UTC, jecarr approved these changes

2023-03-06 13:10 UTC, merged