Update README.md
arachne-threat-intel/thread pull request #69
Opened 2023-08-19 11:12 UTC by KadeMorton

I've made some preliminary changes to the Thread README to help emphasise the community building we want to do around the the project.

2023-08-22 15:29 UTC, jecarr requested changes
Nice work, Kade!

Regarding a spellcheck, I did spot American-English spellings across the new files but as there are quite a few, I didn't flag them; if it's your preference let's leave it like that.

2023-08-22 15:29 UTC, jecarr commented on PERSONAS.md
> +### Persona 3: Beatrix, IT Administrator
Should be

```
## Persona 3: Beatrix, IT Administrator
```

Beatrix's header is currently smaller, she's just as important 😉

2023-08-22 15:32 UTC, jecarr commented on ROADMAP.md
Commenting to make clear this point is about your numbered bullet points in the roadmap file

2023-09-04 09:10 UTC, KadeMorton commented on README.md
> +* [Understanding MITRE ATT&CK, TTPs and how to leverage them](#understanding-mitre-att&ck-ttps-and-how-to-leverage-them)
As discussed we will fix this!

2023-09-04 09:16 UTC, KadeMorton commented on PERSONAS.md
> +### Persona 3: Beatrix, IT Administrator
As discussed we will fix this.

2023-09-29 14:17 UTC, jecarr commented on README.md
> +Copyright 2023 Arachne Digital
We've been inconsistent with this.

We initially didn't update the year because of the whole "use the earliest date of publication" rule - see https://www.copyrightlaws.com/copyright-symbol-notice-year/ - so we hadn't updated the NOTICE.txt copyright year. But we updated the year on our live website. Was this from talks with lawyers?

Just raising a comment to say let's confirm what year we're stating and make this the same across the NOTICE file, here, and live site.

2023-09-29 17:50 UTC, jecarr requested changes
I've added Coding Standards and done some other tweaks - please review my changes. Marked as requesting-changes because there's a point I removed where I didn't know how to replace.

2023-09-29 17:50 UTC, jecarr commented on CONTRIBUTING.md
> +* Commit Messages and Changelogs: Our detailed changelog includes the names of contributors next to the changes or features they have introduced. This makes it easy for users and fellow contributors
I removed `Authorship and Credits` as your suggestion for `// author` in-line comments will get very repetitive. Could you please re-phrase/think of a different mechanism on how we achieve that bullet point?

[Related discussion](https://stackoverflow.com/a/28048085) states how Django does it and I'm leaning towards that.

2023-10-04 09:26 UTC, jecarr commented on README.md
> +Copyright 2023 Arachne Digital
Confirmed with @KadeMorton all years will be current year. I'll check where we have 2021 listed.

2023-10-06 09:39 UTC, jecarr commented on README.md
> +Copyright 2023 Arachne Digital
I've checked this and we're fine! Our LICENSE file says 2021 because we are saying "Written by us dated 2021". Our NOTICE file contains 2021 because that's part of the Bootstrap licence which we copied without editing.

2023-10-06 10:16 UTC, jecarr commented on CONTRIBUTING.md
> +* Commit Messages and Changelogs: Our detailed changelog includes the names of contributors next to the changes or features they have introduced. This makes it easy for users and fellow contributors
As agreed, we're liking the AUTHORS file approach, and I've got some points to ask/raise:

- I found a way to generate it via this discussion: https://github.com/vlang/v/discussions/10025
- I can have a think too but have you got some introductory-text you want to preface the authors-list?
   - [Django's file](https://github.com/django/django/blob/4.2.6/AUTHORS) as an example
   - [Google's docs](https://opensource.google/documentation/reference/releasing/authors) as another example
- Django's file has `Name <email>`
   - Some entries have just the name; some have `Name <website>`
   - Should I just put the name and in PRs/Slack we ask a user (who we are adding to the AUTHORS file) whether they want accompanying information?

2023-10-07 03:52 UTC, KadeMorton commented on CONTRIBUTING.md
> +* Commit Messages and Changelogs: Our detailed changelog includes the names of contributors next to the changes or features they have introduced. This makes it easy for users and fellow contributors
Below is some suggested text.

I think the original authors deserve to go in the Special Thanks area since this was their idea initially, and we probably want a broader MITRE ATT&CK one as well.

Let's just go with the name as far as what we put in as default, we can ask the contributor if they want accompanying information. 

# Thread Project - AUTHORS

We would like to extend our heartfelt thanks and recognition to the following individuals who have contributed their time, expertise, and dedication to the Thread project. Your efforts have played a significant role in shaping and improving this open source project.

## Core Contributors

- [Full Name](https://github.com/username)
  - Role: Describe their role (e.g., Developer, Maintainer)

## Contributors

- [Full Name](https://github.com/username)

## Special Thanks

- [Full Name](https://github.com/username)
  - Reason for Thanks: Explain why this individual deserves special recognition, such as exceptional contributions or leadership.

## Community Contributors

We also want to express our gratitude to the broader Thread community for your support, feedback, and contributions. Your involvement is crucial to the continued success and growth of this project.

If you have contributed to Thread, and your name is missing or you would like to update your information, please submit a pull request to this file, and we'll be happy to include you.

Thank you to everyone who has helped make Thread a thriving open source community!

2023-10-09 11:32 UTC, jecarr commented on CONTRIBUTING.md
> +* Commit Messages and Changelogs: Our detailed changelog includes the names of contributors next to the changes or features they have introduced. This makes it easy for users and fellow contributors
Ok, I've added an initial Authors file https://github.com/arachne-threat-intel/thread/blob/KadeMorton-patch-1/AUTHORS

- I opted for a non-markdown version as I liked how Django did theirs
  - I thought removing the headers and GitHub hyperlinks would add more focus to the names/authors which is a goal of the file
  - It's really easy to convert back to markdown though (what your comment above is) so if you want the layout your comment above has, let me know and I'll change the file
- I've added full names where their GitHub profile shows the full name
  - I am able to provide full names for the couple that I am missing in my initial commit
    - *but* as they themselves have not disclosed their full names on their GitHub profiles, I'll refrain from disclosing them without permission
    - A full name is there without a GitHub link as that is the only info I had from the generated-authors list
  - In the future, we'll ask users to state their preference on how they want to be credited
- Let me know if I've credited you incorrectly!

2023-10-09 13:08 UTC, jecarr commented
In addition to the Authors file, I also edited the Contributing doc. Similarly to an earlier review-comment, I found the bullet point lists a bit easier to read if the indents weren't overlapping. 

Rationale:

1. Markdown automatically indents a numbered point

You had supporting text for point number 1

- You then had a sub-list for the supporting text but the indent shows it at the same level as point number 1

So I took how you handled the numbered points in [Enforcement Guidelines](https://github.com/arachne-threat-intel/thread/blob/KadeMorton-patch-1/CODE_OF_CONDUCT.md#enforcement-guidelines) and applied it to the Contributing doc. Feel free to revert 8f904f5 if you think it reads better as it was before.

2023-10-10 08:13 UTC, KadeMorton commented on CONTRIBUTING.md
> +* Commit Messages and Changelogs: Our detailed changelog includes the names of contributors next to the changes or features they have introduced. This makes it easy for users and fellow contributors
Discussed and resolved.

2023-10-10 08:20 UTC, merged

2023-10-10 08:20 UTC, jecarr commented
Discussed and merged